// console.dir(document);
// console.log(document.domain);
// console.log(document.URL);
// console.log(document.title);
// document.title=123;
// console.log(document.doctype);
// console.log(document.head);
// console.log(document.body);
// console.log(document.all);
// console.log(document.all[10]);
// document.all[10].textContent='Hello';
// console.log(document.forms[0]);
var header=document.getElementById('main-header');
header.style.borderBottom='solid 1px #000';
var addItem=document.getElementsByClassName('title');
addItem[0].style.fontWeight="bold";
addItem[0].style.color='green';